#!/bin/bash
brightness=$(($(cat /sys/class/backlight/intel_backlight/brightness)/192))
if [ $brightness -gt 50 ]; then
    echo "<span color='#ff0000'> $brightness%</span>"
else
    echo "<span color='#00ff00'> $brightness%</span>"
fi
