#!/bin/bash
temp=$(sensors | grep "Core 0" | awk '{ print $3 }' | cut -d. -f1 | cut -b2-)
if [ $temp -le 60 ]; then
    echo "<span color='#00ff00'> $temp°C</span>"
else
    echo "<span color='#ff0000'> $temp°C</span>"
fi
