#!/bin/bash
selection=$(cat ~/.scripts/emoji | dmenu -p emoji -l 5 | awk '{print $1}' &)
[[ -z $selection ]] && notify-send ":( Nothing Entered" && exit 1
printf "$selection" | xclip -selection clipboard && notify-send "$selection copied to clipboard!" && exit 0
