#!/bin/bash
usage=$(free | awk '/^Mem/ {print $3}')
[[ $usage -lt 1572864 ]] && echo "<span color='#00ff00'> $(free -h | awk '/^Mem/ {print $3}')</span>" || echo "<span color='#ff0000'> $(free -h | awk '/^Mem/ {print $3}')</span>"
